logging:
  file:
    name: 'C:/Users/Developer/Desktop/contenedor/app-api.log'
  level:
    root: INFO
    com.mx.core: INFO
    org.springframework.boot.actuate.endpoint.EndpointId: ERROR
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
              BasicExtractor: WARN
  pattern:
    console: >-
      %d{dd-MM-yyyy HH:mm:ss.SSS} %X{op} %X{id} - %magenta([%thread])
      %highlight(%-5level) %logger{0}.%M - %msg%n
    file: '%d{dd-MM-yyyy HH:mm:ss.SSS} %X{op} %X{id} - %-5level %logger{0} - %msg%n'
  RollingFile:
    filePattern: 'logs/archive/rollingfile.log.%d{yyyy-MM-dd-hh-mm}.gz'
    PatternLayout:
      pattern: '[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n'
    DefaultRollOverStrategy:
      max: 30
